In [1]:
import numpy as np
gb_file_path="C:/Users/Administrator/data_analysis_course/P16 本地数据读取/GBvideos.csv"

In [2]:
t1=np.loadtxt(gb_file_path,delimiter=",",dtype="int64")
print(t1)

[[     28 7426393   78240   13548     705]
 [     24  494203    2651    1309       0]
 [     24  142819   13119     151    1141]
 ..., 
 [     26   96935    3537     291     589]
 [     24 2259132   38692    1573    4566]
 [     24  110540     726      38      49]]


In [3]:
t1.transpose()

array([[     28,      24,      24, ...,      26,      24,      24],
       [7426393,  494203,  142819, ...,   96935, 2259132,  110540],
       [  78240,    2651,   13119, ...,    3537,   38692,     726],
       [  13548,    1309,     151, ...,     291,    1573,      38],
       [    705,       0,    1141, ...,     589,    4566,      49]], dtype=int64)

In [4]:
print(t1[2])
print(t1[3,4])
print(type(t1[3,4]))

[    24 142819  13119    151   1141]
3598
<class 'numpy.int64'>


In [5]:
print(t1[2])
print(t1[2:])
print(t1[[1,3]])

[    24 142819  13119    151   1141]
[[     24  142819   13119     151    1141]
 [      1 1580028   65729    1529    3598]
 [     26   40592    5019      57     490]
 ..., 
 [     26   96935    3537     291     589]
 [     24 2259132   38692    1573    4566]
 [     24  110540     726      38      49]]
[[     24  494203    2651    1309       0]
 [      1 1580028   65729    1529    3598]]


In [6]:
print(t1[2,:])
print(t1[2:,:])
print(t1[[1,6,5],:])

[    24 142819  13119    151   1141]
[[     24  142819   13119     151    1141]
 [      1 1580028   65729    1529    3598]
 [     26   40592    5019      57     490]
 ..., 
 [     26   96935    3537     291     589]
 [     24 2259132   38692    1573    4566]
 [     24  110540     726      38      49]]
[[    24 494203   2651   1309      0]
 [    26 479291  23935    638   1941]
 [    24 317696   9449    135    464]]


In [7]:
print(t1[:,2])
print(t1[:,2:])
print(t1[:,[1,3,4]])
print(t1[2:6,1:3])
print(t1[[1,4,5],[2,3,4]])

[  78240    2651   13119   65729    5019    9449   23935  384841    2761
   42272   65988   14916   61352   16251   19564   12172   66290    5470
   39633   25455    1126    5388    9523   74528      62   53795    2094
   15787    7658   17509    8915    4209  104889   14093    9213   10659
   17100   26446     108    4041    5311     490    9278   26518    9886
    1906   19533   41072    6298   18020    6060    9465    2566    2921
   15307   14276    3986  190937    6684    1302    3821     761   11767
   22255    9743    1068   19869   83410    2543   45401    3105  155585
   16287    2376    1690    6155    6543    3299    5830    4811   13349
    8235   13098    8048    3964   57541   17140    4631     196    5982
   47532  183473   15347     805       0    5496  468496     393   19733
   15693    2193    6301      80     839  133815    3337      63   12097
   50006   49246 1431489   17086     100   29748     268     264   20499
     859     167   17703    4772     335   49441   

In [8]:
t1<1000

array([[ True, False, False, False,  True],
       [ True, False, False, False,  True],
       [ True, False, False,  True, False],
       ..., 
       [ True, False, False,  True,  True],
       [ True, False, False, False, False],
       [ True, False,  True,  True,  True]], dtype=bool)

In [9]:
t1[t1<100]=0
print(t1)

[[      0 7426393   78240   13548     705]
 [      0  494203    2651    1309       0]
 [      0  142819   13119     151    1141]
 ..., 
 [      0   96935    3537     291     589]
 [      0 2259132   38692    1573    4566]
 [      0  110540     726       0       0]]


In [10]:
import random
t1=t1.astype(float)

In [11]:
t1[t1<100]=random.random()
print(t1)

[[  8.85614340e-01   7.42639300e+06   7.82400000e+04   1.35480000e+04
    7.05000000e+02]
 [  8.85614340e-01   4.94203000e+05   2.65100000e+03   1.30900000e+03
    8.85614340e-01]
 [  8.85614340e-01   1.42819000e+05   1.31190000e+04   1.51000000e+02
    1.14100000e+03]
 ..., 
 [  8.85614340e-01   9.69350000e+04   3.53700000e+03   2.91000000e+02
    5.89000000e+02]
 [  8.85614340e-01   2.25913200e+06   3.86920000e+04   1.57300000e+03
    4.56600000e+03]
 [  8.85614340e-01   1.10540000e+05   7.26000000e+02   8.85614340e-01
    8.85614340e-01]]


In [12]:
t1=t1*10
t1=t1.astype(int)

In [13]:
print(t1)

[[       8 74263930   782400   135480     7050]
 [       8  4942030    26510    13090        8]
 [       8  1428190   131190     1510    11410]
 ..., 
 [       8   969350    35370     2910     5890]
 [       8 22591320   386920    15730    45660]
 [       8  1105400     7260        8        8]]


In [14]:
t1=np.where(t1<200,88,t1)
print(t1)

[[      88 74263930   782400   135480     7050]
 [      88  4942030    26510    13090       88]
 [      88  1428190   131190     1510    11410]
 ..., 
 [      88   969350    35370     2910     5890]
 [      88 22591320   386920    15730    45660]
 [      88  1105400     7260       88       88]]


In [15]:
t1.clip(100,5000)

array([[ 100, 5000, 5000, 5000, 5000],
       [ 100, 5000, 5000, 5000,  100],
       [ 100, 5000, 5000, 1510, 5000],
       ..., 
       [ 100, 5000, 5000, 2910, 5000],
       [ 100, 5000, 5000, 5000, 5000],
       [ 100, 5000, 5000,  100,  100]])

In [21]:
print(t1)
t1=t1.astype(float)
t1[[1,4,5],[1,2,4]]=np.nan

[[  8.80000000e+01   7.42639300e+07   7.82400000e+05   1.35480000e+05
    7.05000000e+03]
 [  8.80000000e+01   4.94203000e+06   2.65100000e+04   1.30900000e+04
    8.80000000e+01]
 [  8.80000000e+01   1.42819000e+06   1.31190000e+05   1.51000000e+03
    1.14100000e+04]
 ..., 
 [  8.80000000e+01   9.69350000e+05   3.53700000e+04   2.91000000e+03
    5.89000000e+03]
 [  8.80000000e+01   2.25913200e+07   3.86920000e+05   1.57300000e+04
    4.56600000e+04]
 [  8.80000000e+01   1.10540000e+06   7.26000000e+03   8.80000000e+01
    8.80000000e+01]]


In [22]:

np.count_nonzero(t1!=t1)


3

In [23]:
np.count_nonzero(np.isnan(t1))

3

In [24]:
np.isnan(t1)

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       ..., 
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [25]:
np.where(np.isnan(t1))

(array([1, 4, 5], dtype=int64), array([1, 2, 4], dtype=int64))