In [14]:
import numpy as np
gb_file_path="C:/Users/Administrator/data_analysis_course/P16 本地数据读取/GBvideos.csv"

In [18]:
t1=np.loadtxt(gb_file_path,delimiter=",",dtype="int64")
print(t1)

[[     28 7426393   78240   13548     705]
 [     24  494203    2651    1309       0]
 [     24  142819   13119     151    1141]
 ..., 
 [     26   96935    3537     291     589]
 [     24 2259132   38692    1573    4566]
 [     24  110540     726      38      49]]


In [19]:
t1.transpose()

array([[     28,      24,      24, ...,      26,      24,      24],
       [7426393,  494203,  142819, ...,   96935, 2259132,  110540],
       [  78240,    2651,   13119, ...,    3537,   38692,     726],
       [  13548,    1309,     151, ...,     291,    1573,      38],
       [    705,       0,    1141, ...,     589,    4566,      49]], dtype=int64)