In [1]:
import numpy as np
t1=np.array([1,2,3,4,5,6,7])
print(t1)

In [3]:
t2=np.array(range(10))
print(t2)

In [9]:
t2=np.array(range(1,10))
print(t2)
print(type(t2))
t2=np.array(range(1,10),dtype=float)
print(t2.dtype)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
float64


In [15]:
t3=np.array([1,0,1,0,1,0,1])
print(t3.dtype)
t3=np.array([1,0,1,0,1,0,1],dtype=bool)
print(t3)
t4=t3.astype(int)
print(t4,t4.dtype)

int32
[ True False  True False  True False  True]
[1 0 1 0 1 0 1] int32


In [18]:
import random
t5=np.array([random.random() for i in range(10)])
print(t5)

[ 0.40463894  0.31859588  0.98586756  0.67369847  0.02785173  0.52386744
  0.82780557  0.26526613  0.26353505  0.53189512]


In [19]:
print(np.round(t5,2))

[ 0.4   0.32  0.99  0.67  0.03  0.52  0.83  0.27  0.26  0.53]
