In [5]:
import numpy as np
t1=np.arange(12)
print(t1)
t1.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11]


(12,)

In [6]:
t2=np.array([[1,2,3,4],[5,6,7,8,]])
t2.shape

(2, 4)

In [14]:
t3=np.array([[[1,2,3,8,3,8,3,8],[4,5,6,5,3,8,3,8]],[[7,8,9,4,3,8,3,8],[10,11,12,5,3,8,3,8]]])
print(t3)
t3.shape
t3.reshape(3,2,2)
print(t3)
t3.reshape(4,2,2,2)

[[[ 1  2  3  8  3  8  3  8]
  [ 4  5  6  5  3  8  3  8]]

 [[ 7  8  9  4  3  8  3  8]
  [10 11 12  5  3  8  3  8]]]


(2, 2, 8)

In [17]:
t1/0

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,
        inf])

In [24]:
t2=np.arange(1,13)
print(t2)
t2=t2.reshape((3,4))
print(t2)
t3=np.arange(1,4).reshape((3,1))
print(t3)
t2-t3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1]
 [2]
 [3]]


array([[0, 1, 2, 3],
       [3, 4, 5, 6],
       [6, 7, 8, 9]])

In [36]:
t4=np.arange(24).reshape((3,4,2))
t5=np.arange(8).reshape((4,2))
t6=np.arange(12).reshape((3,4))
print(t4)
print(t5)
print(t6)
t4-t5



[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 8,  8],
        [ 8,  8],
        [ 8,  8],
        [ 8,  8]],

       [[16, 16],
        [16, 16],
        [16, 16],
        [16, 16]]])

In [38]:
#t4-t6算不了