In [1]:
import numpy as np

In [2]:
t1=np.arange(12).reshape((3,4))
t2=np.arange(12,24).reshape((3,4))

In [3]:
print(t1,t2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [4]:
np.vstack((t1,t2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
np.hstack((t1,t2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [6]:
gb_file_path="C:/Users/Administrator/data_analysis_course/P16 本地数据读取/GBvideos.csv"
t1=np.loadtxt(gb_file_path,delimiter=",",dtype="int64")
print(t1)

[[     28 7426393   78240   13548     705]
 [     24  494203    2651    1309       0]
 [     24  142819   13119     151    1141]
 ..., 
 [     26   96935    3537     291     589]
 [     24 2259132   38692    1573    4566]
 [     24  110540     726      38      49]]


In [7]:
gb_file_path="C:/Users/Administrator/data_analysis_course/P16 本地数据读取/USvideos.csv"
t2=np.loadtxt(gb_file_path,delimiter=",",dtype="int64")
print(t2)

[[      24  4394029   320053     5931    46245]
 [      28  7860119   185853    26679        0]
 [      22  5845909   576597    39774   170708]
 [      28  2642103    24975     4542    12829]
 [      23  1168130    96666      568     6666]
 [       1  1311445    34507      544     3040]
 [      23   666169     9985      297     1071]
 [      28  1728614    74062     2180    15297]
 [      22  1338533    69687      678     5643]
 [       1  1056891    29943      878     4046]
 [      23   859289    34485      726     1914]
 [      23   452477    28050      405     2745]
 [      23   258781     8085      303      726]
 [      24   274358     9215      477      838]
 [      24   473691    14740      415     1696]
 [      28   514972    18936      641     3817]
 [      24   282858    14870      300     1398]
 [       1  1582683    65749     1531     3598]
 [      26   479951    23945      640     1941]
 [       1  2693468     7941      302     1432]
 [      10   815608    66420     3578   

In [23]:
a=np.array([[1 for i in range(1,np.size(t1,0)+1)]]).reshape(np.size(t1,0),1)
print(a)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]


In [24]:
np.size(t1,0)

921

In [25]:
np.size(a)

921

In [26]:
t1=np.hstack((t1,a))


In [27]:
t1

array([[     28, 7426393,   78240,   13548,     705,       1],
       [     24,  494203,    2651,    1309,       0,       1],
       [     24,  142819,   13119,     151,    1141,       1],
       ..., 
       [     26,   96935,    3537,     291,     589,       1],
       [     24, 2259132,   38692,    1573,    4566,       1],
       [     24,  110540,     726,      38,      49,       1]], dtype=int64)

In [29]:
b=np.array([[0 for i in range(1,np.size(t2,0)+1)]]).reshape(np.size(t2,0),1)
print(b)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [30]:
t2=np.hstack((t2,b))

In [31]:
t=np.vstack((t1,t2))

In [32]:
print(t)

[[     28 7426393   78240   13548     705       1]
 [     24  494203    2651    1309       0       1]
 [     24  142819   13119     151    1141       1]
 ..., 
 [     28  148998    2123     101     435       0]
 [     20  182676    3752     165    1163       0]
 [     23  379817   14096     323    1338       0]]


In [33]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [34]:
np.argmax(t,axis=0)

array([114, 592, 572, 923, 923,   0], dtype=int64)

In [35]:
np.argmin(t,axis=1)

array([5, 4, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5,
       5, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 0, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 3, 0, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 3, 5, 0, 5, 5, 0, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 0, 5, 5, 0, 5, 5, 0, 0, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 0, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4,
       5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5,