In [3]:
import numpy as np
np.random.seed(10)
t1=np.random.randint(10,50,(5,6))
print(t1)

[[19 46 25 10 38 35]
 [39 39 18 19 10 46]
 [26 46 21 34 43 18]
 [46 24 23 15 23 35]
 [23 38 32 40 40 35]]


In [4]:
t1=np.where(t1==40,np.nan,t1)

In [5]:
print(t1)

[[ 19.  46.  25.  10.  38.  35.]
 [ 39.  39.  18.  19.  10.  46.]
 [ 26.  46.  21.  34.  43.  18.]
 [ 46.  24.  23.  15.  23.  35.]
 [ 23.  38.  32.  nan  nan  35.]]


In [6]:
t1.sum(axis=0)

array([ 153.,  193.,  119.,   nan,   nan,  169.])

In [7]:
t1.mean(axis=0)

array([ 30.6,  38.6,  23.8,   nan,   nan,  33.8])

In [9]:
np.median(t1,axis=0)

D:\Anaconda\lib\site-packages\numpy\lib\function_base.py:4016: RuntimeWarning: Invalid value encountered in median for 2 results
  r = func(a, **kwargs)


array([ 26.,  39.,  23.,  nan,  nan,  35.])

In [11]:
t1.ptp(axis=0)

array([ 27.,  22.,  14.,  nan,  nan,  28.])

In [12]:
t1.std(axis=0)

array([ 10.20979921,   8.0399005 ,   4.70744092,          nan,
                nan,   8.97552227])