In [1]:
#1）for, if 都要加：
#2）定义函数：def,return, if__name='__main__'
#3)判断缺失值个数np.count_nonzero(isnan())
#4)常用思想是直接把缺失值的位置赋值为平均值
#5）注意缩进的匹配
import numpy as np


In [2]:
def fill_ndarray(t1):
   for i in range(t1.shape[1]):
       temp_col=t1[:,i]
       nan_nums=np.count_nonzero(np.isnan(temp_col))#判断缺失值的个数
       if nan_nums!=0:
           temp_not_nan_col=temp_col[temp_col==temp_col]#当前不为nan的array
           temp_col[np.isnan(temp_col)]=temp_not_nan_col.mean()#把nan替换为均值
   return t1

In [3]:
if __name__=='__main__':
   t1=np.arange(12).reshape((3,4)).astype('float')
   t1[1,2:]=np.nan
   print(t1)
   t1=fill_ndarray(t1)
   print(t1)

[[  0.   1.   2.   3.]
 [  4.   5.  nan  nan]
 [  8.   9.  10.  11.]]
[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]
